### ISSUE TITLE
Username characters set

### ISSUE THREAD

**Issue by BoboTiG** [timovn/blogotext#57]
On the dev branch, I can no longer use my username when validating the preferences form.
Is it possible to allow `-` and other signs like `.`? These are quite common.

**Comment by timovn** [comment]
I changed that because of some characters causing trouble in the INI file and it’s escaping rules not recognised by [parse_ini_file](http://php.net/manual/fr/function.parse-ini-file.php).

I don’t wish to use any custom parser, so I need to refuse at least _some_ characters.

The chars I need to refuse that I know of are `=`, `'` `"` and `\` (see discussion in PHP man page).
If you know any others, please share, otherwise, yes, I could easilly change my whitelist `[\w ]` to a blacklist `[^="'\\]`.

**Comment by BoboTiG** [comment]
`\w` is really restrictive. Accents are not valid too.
Personally I think it is a good idea to change the whitelist for a blacklist. I looked into the [Python ConfigParser module](https://hg.python.org/cpython/file/3.5/Lib/configparser.py#l589) and it adds `|` as delimiter, but it does not seem to be useful here.

**Comment by timovn** [comment]
`\w` will take into account diacritics if you use the `u` flag
```
preg_match('#\w#u', 'é')  // returns TRUE
```

I will change all this for a blacklist.
I’ll add `|` just in case. No normal person will use this in his name, but there are always weirdos^^.

**Comment by BoboTiG** [comment]
OK great!
Good point for the `u` flag.

**Comment by timovn** [comment]
Crap, still forgot the `|`…
I’ll add it on next commit.
